package group2.tier2csep3.networking.util;

public enum NetworkType {

    COMPONENTS,
    BUILDS,
    LOGIN,
    REGISTER,
    CONNECTION,
    ADDNEWCOMPONENT,
    DELETEACCOUNT,
    EDITACCOUNT,
    POSTS,
    OTHERACCOUNT,
    ADDBUILD,
    EDITBUILD,
    DELETEBUILD,
    ADDPOST,
    RATINGBUILDS,
    RATINGCOMPONENTS,
    RATINGPOSTS,
    POSTCOMMENT,
    SAVEPOST,
    DELETEPOST,
    REPORT
}
